create table schedules
(
    id        bigint generated by default as identity
        primary key,
    doctor_id bigint  not null
        constraint doctor_fk
            references doctors,
    monday    boolean not null,
    tuesday   boolean not null,
    wednesday boolean not null,
    thursday  boolean not null,
    friday    boolean not null,
    saturday  boolean not null,
    sunday    boolean not null
);

grant delete, insert, references, select, trigger, truncate, update on schedules to new_db_admin;