create table timetable
(
    id            bigint generated by default as identity
        primary key,
    doctor_id     bigint    not null
        constraint doctor_fk
            references doctors,
    date_and_time timestamp not null,
    patient_id    bigint
        constraint patient_fk
            references patients
);

grant delete, insert, references, select, trigger, truncate, update on schedules to new_db_admin;